###############################################################
# GNU Make Makefile for Win32 - MS VC++ 16.0

CC = cl -nologo /std:c++14 /Zc:__cplusplus /permissive-

OBJS := $(patsubst %.cpp,%.obj,$(wildcard postproc/*.cpp) $(wildcard *.cpp))

.SUFFIXES:
.SUFFIXES: .cpp .obj
.PHONY: clean

postproc.exe: $(OBJS)
	$(CC) -Fe$@ $^ /link __vic14.lib pcre.lib

.cpp.obj:
	$(CC) -EHsc -DPCRE_STATIC -O2 -Ob1 -GF -c -I. -Fo$@ $<

clean:
	-del /F /Q *.obj postproc\*.obj postproc.exe 2>nul
